In [ ]:
import torch
from torch import nn

torch.manual_seed(123)
batch_example = torch.randn(2, 5)
display(batch_example)
layer = nn.Sequential(nn.Linear(5, 6), nn.ReLU())
out = layer(batch_example)
display(out)
display(batch_example.mean(dim=-1, keepdim=True), batch_example.var(dim=-1, keepdim=True))
display(out.mean(dim=-1, keepdim=True), out.var(dim=-1, keepdim=True))

tensor([[-0.1115,  0.1204, -0.3696, -0.2404, -1.1969],
        [ 0.2093, -0.9724, -0.7550,  0.3239, -0.1085]])

tensor([[0.2260, 0.3470, 0.0000, 0.2216, 0.0000, 0.0000],
        [0.2133, 0.2394, 0.0000, 0.5198, 0.3297, 0.0000]],
       grad_fn=<ReluBackward0>)

tensor([[-0.3596],
        [-0.2606]])

tensor([[0.1324],
        [0.2170]], grad_fn=<MeanBackward1>)